"""Add tokens_limit and is_active to users

Revision ID: 9ad84fdbc9fa
Revises: 
Create Date: 2026-04-15 16:31:49.013250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ad84fdbc9fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add plan and tokens_limit columns if they don't exist
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True, server_default='free'))
    op.add_column('users', sa.Column('tokens_limit', sa.Integer(), nullable=True, server_default='10000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_limit')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
